export const FETCT_WEATHER_PENDING ="FETCT_WEATHER_PENDING" ;
export const FETCT_CURRENT_SUCCESS ="FETCT_CURRENT_SUCCESS" ;
export const FETCT_WEATHER_FAIL ="FETCT_FORECAST_SUCCESS" ;

export const FETCT_WEATHER_ERROR ="FETCT_WEATHER_ERROR" ;
export const SET_CITY ="SET_CITY" ;
